version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "07:00"
  # Should be bigger than or equal to the total number of dependencies (currently 9)
  open-pull-requests-limit: 15
  target-branch: ci/dependabot-updates
  labels:
  - dependencies
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  target-branch: ci/dependabot-updates
  labels:
  - "CI/CD"
