version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  # Should be bigger than or equal to the total number of dependencies (currently 9)
  open-pull-requests-limit: 15
  target-branch: main
  labels:
  - dependencies
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  target-branch: main
  labels:
  - "CI/CD"
