version: 2
updates:
  # Python
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:21"
      timezone: "Europe/Oslo"
    target-branch: main
    labels:
      - "CI/CD"
      - "dependencies"
      - "skip-changelog"
    groups:
      dependencies:
        dependency-type: "production"

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "05:17"
      timezone: "Europe/Oslo"
    target-branch: main
    labels:
      - "CI/CD"
      - "skip-changelog"
    groups:
      actions:
        patterns: ["*"]
