version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  # Should be bigger than or equal to the total number of dependencies (currently 7)
  open-pull-requests-limit: 10
  target-branch: main
