# pre-commit.ci
ci:
  autofix_commit_msg: |
      [pre-commit.ci] auto fixes from pre-commit hooks

      For more information, see https://pre-commit.ci
  autofix_prs: false
  autoupdate_branch: 'main'
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: 'weekly'
  submodules: false

# hooks
default_language_version:
  python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: debug-statements
  - id: check-yaml
    name: Check YAML
  - id: check-toml
    name: Check TOML
  - id: check-yaml
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.21.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus]

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.9.0
  hooks:
  - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.1
  hooks:
  - id: ruff
    args:
      - --fix
      - --no-unsafe-fixes
      - --show-fixes
      - --exit-non-zero-on-fix

- repo: https://github.com/PyCQA/bandit
  rev: '1.8.6'
  hooks:
  - id: bandit
    args: [-r]
    exclude: ^tests/.*$

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
  hooks:
  - id: mypy
    exclude: ^tests/.*$
    additional_dependencies:
      - "pydantic>=2"

- repo: https://github.com/SINTEF/ci-cd
  rev: v2.9.2
  hooks:
  - id: docs-api-reference
    args:
      - --package-dir=optimade_gateway
      - --full-docs-folder=models
      - --unwanted-file=__init__.py
      - --unwanted-file=run.py
  - id: docs-landing-page
