repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
  - id: trailing-whitespace
    exclude: .*\.md$

- repo: https://github.com/ambv/black
  rev: 21.8b0
  hooks:
  - id: black
    name: Blacken

- repo: https://github.com/PyCQA/bandit
  rev: '1.7.0'
  hooks:
  - id: bandit
    args: [-r]
    exclude: ^tests/.*$

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    exclude: ^tests/.*$

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: python
    types: [python]
    require_serial: true
    exclude: ^tests/.*$
  - id: pytest-plugins
    name: pytest required plugin versions
    entry: invoke
    args: [update-pytest-reqs]
    language: python
    always_run: true
    types: [text]
    pass_filenames: false
    files: ^requirements_dev.txt$
    description: Update the pytest plugins to be minimum the currently listed requirement versions.
