repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: debug-statements
  - id: check-yaml
    name: Check YAML
  - id: check-toml
    name: Check TOML
  - id: check-yaml
  - id: requirements-txt-fixer
    name: Fix requirements*.txt
    files: ^requirements.*\.txt$
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]

- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files", "--skip-gitignore"]
    exclude: ^optimade_gateway/routers/utils.py$

- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
  - id: black

- repo: https://github.com/PyCQA/bandit
  rev: '1.7.5'
  hooks:
  - id: bandit
    args: [-r]
    exclude: ^tests/.*$

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.3.0
  hooks:
  - id: mypy
    exclude: ^tests/.*$
    additional_dependencies:
      - "pydantic"

- repo: https://github.com/SINTEF/ci-cd
  rev: v2.3.1
  hooks:
  - id: docs-api-reference
    args:
      - --package-dir
      - optimade_gateway
      - --full-docs-folder
      - models
  - id: docs-landing-page

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: python
    types: [python]
    require_serial: true
    exclude: ^tests/.*$
  - id: pytest-plugins
    name: pytest required plugin versions
    entry: invoke
    args: [update-pytest-reqs]
    language: python
    always_run: true
    types: [text]
    pass_filenames: false
    files: ^requirements_dev.txt$
    description: Update the pytest plugins to be minimum the currently listed requirement versions.
  # - id: update-docs-api-reference
  #   name: Update API Reference in Documentation
  #   entry: invoke
  #   args: [create-api-reference-docs, --pre-clean, --pre-commit]
  #   language: python
  #   pass_filenames: false
  #   files: ^optimade_gateway/.*\.py$
  #   description: Update the API Reference documentation, whenever a Python file is touched in the code base.
  # - id: update-docs-index
  #   name: Update Landing Page for Documentation
  #   entry: invoke
  #   args: [create-docs-index]
  #   language: python
  #   pass_filenames: false
  #   files: ^README.md$
  #   description: Update the landing page for the documentation if the source file (README.md) is changed.
