default_language_version:
  python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: end-of-file-fixer
  - id: debug-statements
  - id: check-yaml
    name: Check YAML
  - id: check-toml
    name: Check TOML
  - id: check-yaml
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.2
  hooks:
  - id: pyupgrade
    args: [--py310-plus]

- repo: https://github.com/ambv/black
  rev: 24.3.0
  hooks:
  - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.5
  hooks:
  - id: ruff
    args:
      - --fix
      - --no-unsafe-fixes
      - --show-fixes
      - --exit-non-zero-on-fix

- repo: https://github.com/PyCQA/bandit
  rev: '1.7.8'
  hooks:
  - id: bandit
    args: [-r]
    exclude: ^tests/.*$

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
  - id: mypy
    exclude: ^tests/.*$
    additional_dependencies:
      - "pydantic>=2"

- repo: https://github.com/SINTEF/ci-cd
  rev: v2.7.4
  hooks:
  - id: docs-api-reference
    args:
      - --package-dir=optimade_gateway
      - --full-docs-folder=models
      - --unwanted-file=__init__.py
      - --unwanted-file=run.py
  - id: docs-landing-page
