version: "3"
services:

  db:
    image: mongo:4
    restart: on-failure
    networks:
      - gateway

  optimade-gateway:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG_FILE: "optimade_gateway/config.yml"
    restart: on-failure
    environment:
      CI:
      OPTIMADE_MONGO_URI: "mongodb://db:27017"
    ports:
      - "${PORT:-5000}:80"
    networks:
      - gateway

networks:
  gateway:
