site_name: OPTIMADE Gateway
site_description: Documentation for the OPTIMADE Gateway
site_url: https://www.optimade.org/optimade-gateway/
copyright: Copyright &copy; 2021 Casper Welzel Andersen & THEOS, EPFL

theme:
  name: material
  palette:
    scheme: default
    primary: deep purple
    accent: deep orange
  icon:
    repo: fontawesome/brands/github
  logo: images/optimade_logo_180x180.svg
  favicon: images/favicon.png
  language: en
  features:
    - navigation.instant
    - navigation.top

repo_name: optimade-gateway
repo_url: https://github.com/Materials-Consortia/optimade-gateway
edit_uri: ""

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Materials-Consortia
      name: OPTIMADE on GitHub
    - icon: fontawesome/brands/slack
      link: https://optimade.slack.com
      name: OPTIMADE on Slack

extra_css:
  - css/reference.css

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.tilde
  - toc:
      permalink: true

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: false
            show_root_toc_entry: true
            show_root_full_path: true
            show_object_full_path: false
            show_category_heading: false
            show_if_no_docstring: false
            show_source: true
            group_by_category: true
            heading_level: 2
          selection:
            filters:
              - "!^_[^_]"
              - "!__json_encoder__$"
              - "!__all__$"
              - "!__config__$"
              - "!ValidatorResults$"
            members: true
            inherited_members: false
            docstring_style: google
            docstring_options:
              replace_admonitions: true
      watch:
        - optimade_gateway
  - awesome-pages
