name: CD - Publish & Deploy

on:
  release:
    types:
    - published

jobs:
  update-repo-and-release:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/cd_release.yml@v2.7.1
    if: github.repository == 'Materials-Consortia/optimade-gateway' && startsWith(github.ref, 'refs/tags/v')
    with:
      # General
      git_username: OPTIMADE Developers
      git_email: "dev@optimade.org"
      release_branch: main
      install_extras: "[dev]"

      # PyPI publishing
      python_package: true
      python_version_build: "3.9"
      package_dirs: "optimade_gateway"
      version_update_changes_separator: ";"
      version_update_changes: |
        {package_dir}/__init__.py;__version__ = \".*\";__version__ = \"{version}\"
        {package_dir}/config.json;\"version\": \".*\",;\"version\": \"{version}\",
        tests/static/test_config.json;\"version\": \".*\",;\"version\": \"{version}\",
      build_libs: "flit"
      build_cmd: "flit build"
      publish_on_pypi: false

      # Documentation
      update_docs: true
      python_version_docs: "3.9"
      doc_extras: "[docs]"
      docs_framework: "mkdocs"
    secrets:
      PAT: ${{ secrets.RELEASE_PAT_CASPER }}
