name: CI/CD - New updates to 'main'

on:
  push:
    branches: [main]

jobs:
  update-dependabot-branch-and-docs:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_cd_updated_default_branch.yml@v2.7.1
    if: github.repository_owner == 'Materials-Consortia'
    with:
      # General
      git_username: OPTIMADE Developers
      git_email: "dev@optimade.org"
      default_repo_branch: main

      # Dependabot branch
      permanent_dependencies_branch: ci/dependabot-updates

      # Documentation
      update_docs: true
      update_python_api_ref: true
      package_dirs: optimade_gateway
      update_docs_landing_page: true
      python_version: "3.10"
      doc_extras: "[docs]"
      exclude_files: |
        __init__.py
        run.py
      full_docs_dirs: models
      docs_framework: mkdocs
    secrets:
      PAT: ${{ secrets.RELEASE_PAT_CASPER }}
