name: CI - Check dependencies

on:
  schedule:
    - cron: "30 5 * * 1"
  workflow_dispatch:

jobs:
  check-dependencies:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_check_pyproject_dependencies.yml@v2.7.1
    if: github.repository_owner == 'Materials-Consortia'
    with:
      git_username: OPTIMADE Developers
      git_email: "dev@optimade.org"
      permanent_dependencies_branch: ci/dependabot-updates
      python_version: "3.10"
      install_extras: "[dev]"
      pr_labels: "dependencies"
      ignore: |
        dependency-name=httpx...versions=>=1
        dependency-name=pytest-asyncio...versions=>=0.23.0
    secrets:
      PAT: ${{ secrets.RELEASE_PAT_CASPER }}
