name: CI/CD - New updates to 'main'

on:
  push:
    branches: [main]

jobs:
  update-dependabot-branch-and-docs:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_cd_updated_default_branch.yml@v2.8.3
    if: github.repository_owner == 'Materials-Consortia'
    with:
      # General
      git_username: OPTIMADE Developers
      git_email: "dev@optimade.org"
      default_repo_branch: main

      # Dependabot branch
      update_dependencies_branch: false

      # Documentation
      update_docs: true
      update_python_api_ref: true
      package_dirs: optimade_gateway
      update_docs_landing_page: true
      python_version: "3.10"
      doc_extras: "[docs]"
      exclude_files: |
        __init__.py
        run.py
      full_docs_dirs: models
      docs_framework: mkdocs
    secrets:
      PAT: ${{ secrets.RELEASE_PAT_CASPER }}

  deploy-fly:
    name: Deploy to Fly
    if: github.repository_owner == 'Materials-Consortia'
    runs-on: ubuntu-latest

    environment:
      name: fly
      url: https://optimade-gateway.fly.dev

    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Fly
      uses: superfly/flyctl-actions/setup-flyctl@v1

    - name: Deploy to Fly
      run: flyctl deploy --remote-only -c ./.github/fly.toml
