name: CI - Single Dependabot PR

on:
  schedule:
    # At 8:30 every Wednesday (6:30 UTC)
    # Dependabot runs once a week (every Monday) (pip)
    # and every day (GH Actions) at 7:00 (5:00 UTC)
    - cron: "30 6 * * 3"
  workflow_dispatch:

jobs:
  create-collected-pr:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_update_dependencies.yml@v2.7.1
    if: github.repository_owner == 'Materials-Consortia'
    with:
      # General
      git_username: OPTIMADE Developers
      git_email: "dev@optimade.org"
      permanent_dependencies_branch: ci/dependabot-updates
      default_repo_branch: main

      # Generated PR
      pr_labels: CI/CD,dependencies

      # Pre-commit
      update_pre-commit: true
      python_version: "3.8"
      install_extras: "[dev]"
    secrets:
      PAT: ${{ secrets.RELEASE_PAT_CASPER }}
