name: CI - Keep dependabot branch up-to-date

on:
  push:
    branches: [main]

jobs:

  update-dependabot-branch:
    name: Update permanent dependabot branch
    if: github.repository_owner == 'Materials-Consortia'
    runs-on: ubuntu-latest

    env:
      DEPENDABOT_BRANCH: ci/dependabot-updates
      GIT_USER_NAME: OPTIMADE Developers
      GIT_USER_EMAIL: "dev@optimade.org"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ env.DEPENDABOT_BRANCH }}
        fetch-depth: 0

    - name: Update '${{ env.DEPENDABOT_BRANCH }}'
      run: |
        git config --global user.name "${{ env.GIT_USER_NAME }}"
        git config --global user.email "${{ env.GIT_USER_EMAIL }}"

        git fetch origin
        git merge -m "Keep '${{ env.DEPENDABOT_BRANCH }}' up-to-date with 'main'" origin/main

    - name: Push to '${{ env.DEPENDABOT_BRANCH }}'
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.RELEASE_PAT_CASPER }}
        branch: ${{ env.DEPENDABOT_BRANCH }}
        sleep: 15
