name: Dependabot updates

on:
  schedule:
    # At 8:30 every Monday
    # This matches Dependabot, which runs every Monday (pip) and every day (GH Actions) at 7:00
    - cron: "30 8 * * 1"
  push:
    branches:
      - setup-dependabot-automation

jobs:

  create-collected-pr:
    name: Single dependabot PR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check for dependabot PRs
      run: |
        DEPENDABOT_BRANCHES=($(git branch -rl --format='%(refname:lstrip=3)' | grep -E "^dependabot/(test|github_actions)/.*$" || echo ""))

        echo "NO_OF_BRANCHES=${#DEPENDABOT_BRANCHES[@]}" >> $GITHUB_ENV
        echo "DEPENDABOT_BRANCHES=${DEPENDABOT_BRANCHES[@]}" >> $GITHUB_ENV

    - name: Test
      run: |
        DEPENDABOT_BRANCHES=(${{ env.DEPENDABOT_BRANCHES }})
        for branch in "${DEPENDABOT_BRANCHES[@]}"; do
          echo $branch
        done
