name: Dependabot updates

on:
  schedule:
    # At 8:30 every Monday
    # This matches Dependabot, which runs every Monday (pip) and every day (GH Actions) at 7:00
    - cron: "30 8 * * 1"
  push:
    branches:
      - setup-dependabot-automation

jobs:

  create-collected-pr:
    name: Single dependabot PR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup git config
      run: |
        git config --global user.name "OPTIMADE Developers"
        git config --global user.email "dev@optimade.org"

    - name: Check for dependabot PRs
      run: |
        DEPENDABOT_BRANCHES=($(git branch -rl --format='%(refname:lstrip=2)' | grep -E "^dependabot/(pip|github_actions)/.*$" || echo ""))

        echo "NUMBER_OF_BRANCHES=${#DEPENDABOT_BRANCHES[@]}" >> $GITHUB_ENV
        echo "DEPENDABOT_BRANCHES=${DEPENDABOT_BRANCHES[@]}" >> $GITHUB_ENV

        if [ ! ${#DEPENDABOT_BRANCHES[@]} ]; then
          echo "No dependabot branches found, stopping."
        fi

    - name: Create single branch with updates
      if: env.NUMBER_OF_BRANCHES > 0
      run: |
        DEPENDABOT_BRANCHES=(${{ env.DEPENDABOT_BRANCHES }})

        git checkout -b single_dependabot_pr
        git merge -m "Octopus merge dependencies" "${DEPENDABOT_BRANCHES[@]}"

        if [ $? ]; then
          # Unsuccessful octopus merge
          git merge --abort
        fi

        for branch in "${DEPENDABOT_BRANCHES[@]}"; do
          echo $branch
        done
