name: Dependabot updates

on:
  schedule:
    # At 8:30 every Monday
    # This matches Dependabot, which runs every Monday (pip) and every day (GH Actions) at 7:00
    - cron: "30 8 * * 1"

jobs:

  create-collected-pr:
    name: Create a single PR for all updates
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check for dependabot PRs
      run: |
        DEPENDABOT_BRANCHES=($(git branch -rl --format='%(refname:lstrip=3)' | grep -E "^dependabot/(pip|github_actions)/.*$" || echo ""))

        if [ ! ${#DEPENDABOT_BRANCHES[@]} ]; then
          echo No dependabot branches found
          exit 0
        fi

    - name: Test
      run: |
        echo This shouldn't run
